// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Referent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BackEnd.Entities.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFineEvento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizioEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescrizioneEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LuogoEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Postponed")
                        .HasColumnType("bit");

                    b.Property<int?>("RealEstatePropertyId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RealEstatePropertyId");

                    b.HasIndex("RequestId");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("BackEnd.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("BackEnd.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcquisitionDone")
                        .HasColumnType("bit");

                    b.Property<string>("AdressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Builder")
                        .HasColumnType("bit");

                    b.Property<bool>("Buyer")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GoldCustomer")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OngoingAssignment")
                        .HasColumnType("bit");

                    b.Property<bool>("Other")
                        .HasColumnType("bit");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<bool>("Seller")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BackEnd.Entities.CustomerNotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CalendarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerNotes");
                });

            modelBuilder.Entity("BackEnd.Entities.Documentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Documentation");
                });

            modelBuilder.Entity("BackEnd.Entities.DocumentsTab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BoilerMaintenanceLog")
                        .HasColumnType("bit");

                    b.Property<int?>("BoilerMaintenanceLogDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("BuildingCadastralComplianceReport")
                        .HasColumnType("bit");

                    b.Property<int?>("BuildingCadastralComplianceReportDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("CadastralMapExtract")
                        .HasColumnType("bit");

                    b.Property<int?>("CadastralMapExtractDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("CadastralSurveyAndFloorPlan")
                        .HasColumnType("bit");

                    b.Property<int?>("CadastralSurveyAndFloorPlanDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("ChamberOfCommerceBusinessRegistrySearch")
                        .HasColumnType("bit");

                    b.Property<int?>("ChamberOfCommerceBusinessRegistrySearchDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("CommissionAgreement")
                        .HasColumnType("bit");

                    b.Property<int?>("CommissionAgreementDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("Condominium")
                        .HasColumnType("bit");

                    b.Property<bool>("CondominiumBylaws")
                        .HasColumnType("bit");

                    b.Property<int?>("CondominiumBylawsDocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("CondominiumDocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeedOfOrigin")
                        .HasColumnType("bit");

                    b.Property<int?>("DeedOfOriginDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("DeedOfSale")
                        .HasColumnType("bit");

                    b.Property<int?>("DeedOfSaleDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("ElectricalElectronicSystem")
                        .HasColumnType("bit");

                    b.Property<int?>("ElectricalElectronicSystemDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("EnergyPerformanceCertificate")
                        .HasColumnType("bit");

                    b.Property<int?>("EnergyPerformanceCertificateDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("FireSafetySystem")
                        .HasColumnType("bit");

                    b.Property<int?>("FireSafetySystemDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("FloorPlanWithSubsidiaryUnits")
                        .HasColumnType("bit");

                    b.Property<int?>("FloorPlanWithSubsidiaryUnitsDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("GasSystem")
                        .HasColumnType("bit");

                    b.Property<int?>("GasSystemDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("HabitabilityCertificate")
                        .HasColumnType("bit");

                    b.Property<int?>("HabitabilityCertificateDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("HeatingAirConditioningSystem")
                        .HasColumnType("bit");

                    b.Property<int?>("HeatingAirConditioningSystemDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("IdentificationDocument")
                        .HasColumnType("bit");

                    b.Property<int?>("IdentificationDocumentDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("LandRegistry")
                        .HasColumnType("bit");

                    b.Property<int?>("LandRegistryDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("LastMortgagePaymentReceipt")
                        .HasColumnType("bit");

                    b.Property<int?>("LastMortgagePaymentReceiptDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("LastTwoCondominiumMeetingMinutes")
                        .HasColumnType("bit");

                    b.Property<int?>("LastTwoCondominiumMeetingMinutesDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("LatestFinancialStatementAndBudget")
                        .HasColumnType("bit");

                    b.Property<int?>("LatestFinancialStatementAndBudgetDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("LeaseAgreement")
                        .HasColumnType("bit");

                    b.Property<int?>("LeaseAgreementDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("LiftingSystem")
                        .HasColumnType("bit");

                    b.Property<int?>("LiftingSystemDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("MarriageCertificateSummary")
                        .HasColumnType("bit");

                    b.Property<int?>("MarriageCertificateSummaryDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("MillesimalTables")
                        .HasColumnType("bit");

                    b.Property<int?>("MillesimalTablesDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("MiscellaneousDocuments")
                        .HasColumnType("bit");

                    b.Property<int?>("MiscellaneousDocumentsDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("MortgageDeed")
                        .HasColumnType("bit");

                    b.Property<int?>("MortgageDeedDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("MortgageLienRegistrySearch")
                        .HasColumnType("bit");

                    b.Property<int?>("MortgageLienRegistrySearchDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("PlumbingSanitarySystem")
                        .HasColumnType("bit");

                    b.Property<int?>("PlumbingSanitarySystemDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("PowerOfAttorney")
                        .HasColumnType("bit");

                    b.Property<int?>("PowerOfAttorneyDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("PreliminarySaleAgreement")
                        .HasColumnType("bit");

                    b.Property<int?>("PreliminarySaleAgreementDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("PurchaseOffer")
                        .HasColumnType("bit");

                    b.Property<int?>("PurchaseOfferDocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("RealEstatePropertyDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("SignedStatementFromAdministrator")
                        .HasColumnType("bit");

                    b.Property<int?>("SignedStatementFromAdministratorDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("StructuralIntegrityCertificate")
                        .HasColumnType("bit");

                    b.Property<int?>("StructuralIntegrityCertificateDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("SystemsComplianceDeclaration")
                        .HasColumnType("bit");

                    b.Property<int?>("SystemsComplianceDeclarationDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("TaxCodeOrHealthCard")
                        .HasColumnType("bit");

                    b.Property<int?>("TaxCodeOrHealthCardDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("TaxDeductionDocumentation")
                        .HasColumnType("bit");

                    b.Property<int?>("TaxDeductionDocumentationDocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UrbanPlanningComplianceCertificate")
                        .HasColumnType("bit");

                    b.Property<int?>("UrbanPlanningComplianceCertificateDocumentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DocumentsTabs");
                });

            modelBuilder.Entity("BackEnd.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("BackEnd.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstateProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AgreedCommission")
                        .HasColumnType("int");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AssignmentEnd")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Auction")
                        .HasColumnType("bit");

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommercialSurfaceate")
                        .HasColumnType("int");

                    b.Property<double>("CondominiumExpenses")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Elevators")
                        .HasColumnType("int");

                    b.Property<string>("EnergyClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exposure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlatRateCommission")
                        .HasColumnType("int");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Furniture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Heating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Highlighted")
                        .HasColumnType("bit");

                    b.Property<bool>("InHome")
                        .HasColumnType("bit");

                    b.Property<int>("Kitchens")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MQGarden")
                        .HasColumnType("int");

                    b.Property<string>("MoreDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Negotiation")
                        .HasColumnType("bit");

                    b.Property<string>("OtherFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParkingSpaces")
                        .HasColumnType("int");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("PriceReduced")
                        .HasColumnType("float");

                    b.Property<bool>("Sold")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateOfTheProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StornoProvvigione")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBuildingfloors")
                        .HasColumnType("int");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfAssignment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarehouseRooms")
                        .HasColumnType("int");

                    b.Property<int>("YearOfConstruction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CustomerId");

                    b.ToTable("RealEstateProperties");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstatePropertyNotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CalendarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RealEstatePropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RealEstatePropertyId");

                    b.ToTable("RealEstatePropertyNotes");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstatePropertyPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Highlighted")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("RealEstatePropertyId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RealEstatePropertyId");

                    b.ToTable("RealEstatePropertyPhotos");
                });

            modelBuilder.Entity("BackEnd.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgencyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<bool>("Closed")
                        .HasColumnType("bit");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("GardenFrom")
                        .HasColumnType("int");

                    b.Property<int>("GardenTo")
                        .HasColumnType("int");

                    b.Property<string>("Heating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MQFrom")
                        .HasColumnType("int");

                    b.Property<int>("MQTo")
                        .HasColumnType("int");

                    b.Property<bool>("MortgageAdviceRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParkingSpaces")
                        .HasColumnType("int");

                    b.Property<double>("PriceFrom")
                        .HasColumnType("float");

                    b.Property<double>("PriceTo")
                        .HasColumnType("float");

                    b.Property<string>("PropertyState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("BackEnd.Entities.RequestNotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CalendarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestNotes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BackEnd.Entities.ApplicationUser", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("BackEnd.Entities.Calendar", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("BackEnd.Entities.RealEstateProperty", "RealEstateProperty")
                        .WithMany()
                        .HasForeignKey("RealEstatePropertyId");

                    b.HasOne("BackEnd.Entities.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Customer");

                    b.Navigation("RealEstateProperty");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BackEnd.Entities.City", b =>
                {
                    b.HasOne("BackEnd.Entities.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("BackEnd.Entities.Customer", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("BackEnd.Entities.CustomerNotes", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.Customer", null)
                        .WithMany("CustomerNotes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("BackEnd.Entities.Location", b =>
                {
                    b.HasOne("BackEnd.Entities.City", "City")
                        .WithMany("Locations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstateProperty", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", "Agent")
                        .WithMany("RealEstateProperties")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.Customer", "Customer")
                        .WithMany("RealEstateProperties")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstatePropertyNotes", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.RealEstateProperty", "RealEstateProperty")
                        .WithMany("RealEstatePropertyNotes")
                        .HasForeignKey("RealEstatePropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("RealEstateProperty");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstatePropertyPhoto", b =>
                {
                    b.HasOne("BackEnd.Entities.RealEstateProperty", "RealEstateProperty")
                        .WithMany("Photos")
                        .HasForeignKey("RealEstatePropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealEstateProperty");
                });

            modelBuilder.Entity("BackEnd.Entities.Request", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackEnd.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BackEnd.Entities.RequestNotes", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.Request", null)
                        .WithMany("RequestNotes")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BackEnd.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Entities.ApplicationUser", b =>
                {
                    b.Navigation("RealEstateProperties");
                });

            modelBuilder.Entity("BackEnd.Entities.City", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("BackEnd.Entities.Customer", b =>
                {
                    b.Navigation("CustomerNotes");

                    b.Navigation("RealEstateProperties");
                });

            modelBuilder.Entity("BackEnd.Entities.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("BackEnd.Entities.RealEstateProperty", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("RealEstatePropertyNotes");
                });

            modelBuilder.Entity("BackEnd.Entities.Request", b =>
                {
                    b.Navigation("RequestNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
